[package]
name = "solana-axelar-its"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives.workspace = true
anchor-lang.workspace = true
anchor-spl.workspace = true
solana-axelar-gas-service = { workspace = true, features = ["cpi", "no-entrypoint"] }
solana-axelar-operators = { workspace = true, features = ["no-entrypoint"] }
solana-axelar-gateway = { workspace = true, features = ["cpi", "no-entrypoint"] }
program-utils.workspace = true
bytemuck.workspace = true
bitflags.workspace = true
mpl-token-metadata.workspace = true
spl-token-metadata-interface.workspace = true
interchain-token-transfer-gmp.workspace = true

[dev-dependencies]
solana-axelar-gas-service.workspace = true
bincode.workspace = true
solana-sdk-ids.workspace = true
solana-sdk.workspace = true
mollusk-svm.workspace = true
mollusk-test-utils.workspace = true
mollusk-svm-programs-token.workspace = true
hex.workspace = true
solana-axelar-its-test-fixtures.workspace = true

[package.metadata.cargo-machete]
ignored = ["anchor-spl", "bytemuck", "solana-axelar-gas-service", "solana-axelar-operators"]

[lints]
workspace = true

[lib]
name = "solana_axelar_its"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

cpi = ["no-entrypoint"]
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []
test-sbf = []

devnet-amplifier = [
	"solana-axelar-gas-service/devnet-amplifier",
	"solana-axelar-operators/devnet-amplifier",
]
stagenet = [
	"solana-axelar-gas-service/stagenet",
	"solana-axelar-operators/stagenet",
]
testnet = [
	"solana-axelar-gas-service/testnet",
	"solana-axelar-operators/testnet",
]
mainnet = [
	"solana-axelar-gas-service/mainnet",
	"solana-axelar-operators/mainnet",
]
default = ["devnet-amplifier"]
