[toolchain]
package_manager = "npm"
anchor_version = "1.0.0-rc.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_axelar_gas_service = "gasUBnVr9GZon2cp8X5gyFrUsQFhzrprjy734Ci6Bmn"
solana_axelar_gateway = "gtwT4uGVTYSPnTGv6rSpMheyFyczUicxVWKqdtxNGw9"
solana_axelar_governance = "gov9rPeepKWAL17wJAsy7kdib3ELWjj3kYPBtavkaGc"
solana_axelar_its = "itsYxmqAxNKUL5zaj3fD1K1whuVhqpxKVoiLGie1reF"
solana_axelar_memo = "memKnP9ex71TveNFpsFNVqAYGEe1v9uHVsHNdFPW6FY"
solana_axelar_operators = "oprVNGMBsXzJJBTDQasNWqQ8nZqNhJP2ZXvrC7b5xXd"

[programs.devnet]
solana_axelar_gas_service = "gasUBnVr9GZon2cp8X5gyFrUsQFhzrprjy734Ci6Bmn"
solana_axelar_gateway = "gtwT4uGVTYSPnTGv6rSpMheyFyczUicxVWKqdtxNGw9"
solana_axelar_governance = "gov9rPeepKWAL17wJAsy7kdib3ELWjj3kYPBtavkaGc"
solana_axelar_its = "itsYxmqAxNKUL5zaj3fD1K1whuVhqpxKVoiLGie1reF"
solana_axelar_memo = "memKnP9ex71TveNFpsFNVqAYGEe1v9uHVsHNdFPW6FY"
solana_axelar_operators = "oprVNGMBsXzJJBTDQasNWqQ8nZqNhJP2ZXvrC7b5xXd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
