[toolchain]
package_manager = "npm"
anchor_version = "1.0.0-rc.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_axelar_gas_service = "gas5H48imY2w1j6e6x3EvVxKFtyTuWFhw6pgS5VAPLu"
solana_axelar_gateway = "gtwiF7Bamsq5zBQCnKjK7kHfmBQe7StQE9VPucWrtmA"
solana_axelar_governance = "govxuD1tYtyiGjXiNJBFtRYmuhA68VwJGpGXKADSJxA"
solana_axelar_its = "itspcPS5zL941gd6jJfEAk8NjfzbanDFKtNQCNppVtJ"
solana_axelar_memo = "memxUmZBzudVtrqZGPTuAyKbSZt2LAMkB2itKaUriQR"
solana_axelar_operators = "oprgv1Fc3i2tRLGpKtbMB8oKnQHtWyossGYUfpfPzN6"

[programs.devnet]
solana_axelar_gas_service = "gas5H48imY2w1j6e6x3EvVxKFtyTuWFhw6pgS5VAPLu"
solana_axelar_gateway = "gtwiF7Bamsq5zBQCnKjK7kHfmBQe7StQE9VPucWrtmA"
solana_axelar_governance = "govxuD1tYtyiGjXiNJBFtRYmuhA68VwJGpGXKADSJxA"
solana_axelar_its = "itspcPS5zL941gd6jJfEAk8NjfzbanDFKtNQCNppVtJ"
solana_axelar_memo = "memxUmZBzudVtrqZGPTuAyKbSZt2LAMkB2itKaUriQR"
solana_axelar_operators = "oprgv1Fc3i2tRLGpKtbMB8oKnQHtWyossGYUfpfPzN6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
