[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_axelar_gas_service = "gasHfy8EXRDrxM6XjzrrTBbbqDD3ywnCe29oEEtoTGv"
solana_axelar_gateway = "gtw3LYHmSe3y1cRqCeBuTpyB4KDQHfaqqHQs6Rw19DX"
solana_axelar_governance = "govKw1XM67EFoyLoJ7x6A8qtyJqEw5ZREGfwYxJtYt8"
solana_axelar_its = "itsmM2AJ27dSAXVhCfj34MtnFqyUmnLF7kbKbmyqRQA"
solana_axelar_memo = "mem5NJXuxU7b4UJqq6ib8XUjk1Hnp4z2B1szyRZ8bLv"
solana_axelar_operators = "oprqSRXsywUWMHSLcsLNwYBW3uq4miVq8THceDLcQh8"

[programs.devnet]
solana_axelar_gas_service = "gasHfy8EXRDrxM6XjzrrTBbbqDD3ywnCe29oEEtoTGv"
solana_axelar_gateway = "gtw3LYHmSe3y1cRqCeBuTpyB4KDQHfaqqHQs6Rw19DX"
solana_axelar_governance = "govKw1XM67EFoyLoJ7x6A8qtyJqEw5ZREGfwYxJtYt8"
solana_axelar_its = "itsmM2AJ27dSAXVhCfj34MtnFqyUmnLF7kbKbmyqRQA"
solana_axelar_memo = "mem5NJXuxU7b4UJqq6ib8XUjk1Hnp4z2B1szyRZ8bLv"
solana_axelar_operators = "oprqSRXsywUWMHSLcsLNwYBW3uq4miVq8THceDLcQh8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
