[workspace]
allow_dirty = false # allow updating repositories with uncommitted changes
changelog_update = true # enables changelog updates
dependencies_update = false # update dependencies with `cargo update`
git_release_enable = true # enable GitHub/Gitea releases
git_tag_enable = true # enable GitHub/Gitea tag
pr_branch_prefix = "release-" # PR branch prefix
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_allow_dirty = false # removes `--allow-dirty` to `cargo publish`
semver_check = true # enable API breaking changes checks
publish_timeout = "10m" # set a timeout for `cargo publish`
publish = true
publish_no_verify=false
release = true

pr_body = """
{% for release in releases %}
{% if release.title %}
### {{release.title}}
{% endif %}
Package: {{release.package}} {{release.previous_version}} -> {{release.next_version}}
{% if release.changelog %}
Changes:
{{release.changelog}}
{% endif %}
{% endfor -%}
"""

# Crates

[[package]]
name = "solana-axelar-std"
changelog_path = "CHANGELOG.md"
changelog_update = true
git_release_enable = true
publish = true

[[package]]
name = "governance-gmp"
changelog_path = "CHANGELOG.md"
changelog_update = true
git_release_enable = true
publish = true

# Programs

[[package]]
name = "solana-axelar-operators"
changelog_path = "CHANGELOG.md"
changelog_update = true
git_release_enable = true
publish = true

[[package]]
name = "solana-axelar-gateway"
changelog_path = "CHANGELOG.md"
changelog_update = true
git_release_enable = true
publish = true

[[package]]
name = "solana-axelar-gas-service"
changelog_path = "CHANGELOG.md"
changelog_update = true
git_release_enable = true
publish = true

[[package]]
name = "solana-axelar-its"
changelog_path = "CHANGELOG.md"
changelog_update = true
git_release_enable = true
publish = true

[[package]]
name = "solana-axelar-governance"
changelog_path = "CHANGELOG.md"
changelog_update = true
git_release_enable = true
publish = true
publish_no_verify = true

[[package]]
name = "solana-axelar-memo"
release = true
publish = true
changelog_update = true
git_release_enable = true

[changelog]
header = """# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]
"""

body = """

{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
      {% if commit.breaking %}[**breaking**] {% endif %}\
      {{ commit.message | upper_first }} - \
      ([{{ commit.id | truncate(length=7, end="") }}]({{ remote.link }}/commit/{{ commit.id }}))\
{% endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]({{ release_link }})
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}]
    {% endif %}\
{% endif %}\

{% for group, commits in commits
| filter(attribute="merge_commit", value=false)
| unique(attribute="message")
| group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor -%}
    {% raw %}\n{% endraw %}\
    {%- for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor %}\n

{%- if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
    * @{{ contributor.username }}
{%- endfor %}
{% endif -%}
{%- macro username(commit) -%}
    {% if commit.remote.username %} (by @{{ commit.remote.username }}){% endif -%}
{% endmacro -%}
{%- macro pr(commit) -%}
    {% if commit.remote.pr_number %} - #{{ commit.remote.pr_number }}{% endif -%}
{% endmacro -%}
"""

commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->‚õ∞Ô∏è Features" },
  { message = "^fix", group = "<!-- 1 -->üêõ Bug Fixes" },
  { message = "^doc", group = "<!-- 3 -->üìö Documentation" },
  { message = "^perf", group = "<!-- 4 -->‚ö° Performance" },
  { message = "^refactor\\(clippy\\)", skip = true },
  { message = "^refactor", group = "<!-- 2 -->üöú Refactor" },
  { message = "^style", group = "<!-- 5 -->üé® Styling" },
  { message = "^test", group = "<!-- 6 -->üß™ Testing" },
  { message = "^chore\\(release\\):", skip = true },
  { message = "^chore: release", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^chore\\(npm\\).*yarn\\.lock", skip = true },
  { message = "^chore|^ci", group = "<!-- 7 -->‚öôÔ∏è Miscellaneous Tasks" },
  { body = ".*security", group = "<!-- 8 -->üõ°Ô∏è Security" },
  { message = "^revert", group = "<!-- 9 -->‚óÄÔ∏è Revert" },
]

link_parsers = [
  { pattern = "#(\\d+)", href = "{{ remote.link }}/issues/$1" },
  { pattern = "RFC(\\d+)", text = "ietf-rfc$1", href = "https://datatracker.ietf.org/doc/html/rfc$1" },
]
