[package]
name = "solana-axelar-operators"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
description = "Axelar Operators Anchor program for Solana"

[dependencies]
anchor-lang.workspace = true
solana-axelar-std.workspace = true

[dev-dependencies]
solana-sdk-ids.workspace = true
mollusk-svm.workspace = true
solana-sdk.workspace = true

[lints]
workspace = true

[lib]
name = "solana_axelar_operators"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

cpi = ["no-entrypoint"]
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []
test-sbf = []

devnet-amplifier = []
stagenet = []
testnet = []
mainnet = []
default = ["devnet-amplifier"]
