[package]
name = "solana-axelar-its-legacy"
version = "0.1.0"
edition = "2021"

[lib]
name = "solana_axelar_its_legacy"
crate-type = ["cdylib", "lib"]

[lints]
workspace = true

[features]
no-entrypoint = []
devnet-amplifier = [
	"solana-axelar-gas-service-legacy/devnet-amplifier",
	"solana-axelar-gateway-legacy-test-fixtures/devnet-amplifier",
	"solana-axelar-gateway-legacy/devnet-amplifier",
	"solana-axelar-memo-legacy/devnet-amplifier",
	"program-utils/devnet-amplifier",
]
stagenet = [
	"solana-axelar-gas-service-legacy/stagenet",
	"solana-axelar-gateway-legacy-test-fixtures/stagenet",
	"solana-axelar-gateway-legacy/stagenet",
	"solana-axelar-memo-legacy/stagenet",
	"program-utils/stagenet",
]
testnet = [
	"solana-axelar-gas-service-legacy/testnet",
	"solana-axelar-gateway-legacy-test-fixtures/testnet",
	"solana-axelar-gateway-legacy/testnet",
	"solana-axelar-memo-legacy/testnet",
	"program-utils/testnet",
]
mainnet = [
	"solana-axelar-gas-service-legacy/mainnet",
	"solana-axelar-gateway-legacy-test-fixtures/mainnet",
	"solana-axelar-gateway-legacy/mainnet",
	"solana-axelar-memo-legacy/mainnet",
	"program-utils/mainnet",
]
default = ["devnet-amplifier"]

[dependencies]
anchor-discriminators.workspace = true
anchor-discriminators-macros.workspace = true
alloy-primitives.workspace = true
axelar-solana-encoding.workspace = true
solana-axelar-gas-service-legacy = { workspace = true, features = ["no-entrypoint"] }
solana-axelar-gateway-legacy = { workspace = true, features = ["no-entrypoint"] }
bitflags.workspace = true
borsh.workspace = true
event-cpi-macros.workspace = true
event-cpi.workspace = true
interchain-token-transfer-gmp.workspace = true
itertools.workspace = true
mpl-token-metadata.workspace = true
program-utils = { workspace = true, default-features = false }
role-management.workspace = true
solana-program.workspace = true
solana-sdk-ids.workspace = true
spl-associated-token-account = { workspace = true, features = [
	"no-entrypoint",
] }
spl-token-2022 = { workspace = true, features = [
	"no-entrypoint",
	"serde-traits",
] }
spl-token-metadata-interface.workspace = true
typed-builder.workspace = true

[dev-dependencies]
anyhow.workspace = true
solana-axelar-gateway-legacy-test-fixtures.workspace = true
solana-axelar-memo-legacy = { workspace = true, features = ["no-entrypoint"] }
event-cpi-test-utils.workspace = true
evm-contracts-test-suite.workspace = true
rstest.workspace = true
solana-banks-interface.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
test-context.workspace = true
