[advisories]
ignore = [
  "RUSTSEC-2022-0093", # solana lib dependency
  "RUSTSEC-2024-0344", # solana lib dependency
  "RUSTSEC-2024-0421", # solana lib dependency
  "RUSTSEC-2025-0009", # solana lib dependency
  "RUSTSEC-2024-0370", # alloy lib dependency
  "RUSTSEC-2026-0007", # tokio dependency
] # advisory IDs to ignore e.g. ["RUSTSEC-2019-0001", ...]
