[package]
name = "solana-axelar-test-discoverable"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
description = "Axelar Memo Anchor discoverable program for Solana"
publish = false

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
solana-axelar-gateway = { workspace = true, features = ["cpi"] }
solana-axelar-its = { workspace = true, features = ["cpi", "no-entrypoint"] }
relayer-discovery.workspace = true
anchor-spl.workspace = true
solana-axelar-std.workspace = true
interchain-token-transfer-gmp.workspace = true
program-utils.workspace = true

[dev-dependencies]
solana-axelar-gateway-test-fixtures.workspace = true
mollusk-svm.workspace = true
solana-sdk.workspace = true
bincode.workspace = true
solana-axelar-std.workspace = true
hex.workspace = true
relayer-discovery-test-fixtures.workspace = true
solana-program.workspace = true

[lints]
workspace = true

[lib]
name = "solana_axelar_test_discoverable"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

cpi = ["no-entrypoint"]
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

anchor-debug = []
custom-heap = []
custom-panic = []

# Network features - these pass through to the gateway dependency
devnet-amplifier = [
	"solana-axelar-gateway/devnet-amplifier",
	"solana-axelar-its/devnet-amplifier",
]
stagenet = ["solana-axelar-gateway/stagenet", "solana-axelar-its/stagenet"]
testnet = ["solana-axelar-gateway/testnet", "solana-axelar-its/testnet"]
mainnet = ["solana-axelar-gateway/mainnet", "solana-axelar-its/mainnet"]
default = ["devnet-amplifier"]

[package.metadata.cargo-machete]
ignored = ["anchor-spl"]