# This workflow creates the PR that will trigger the new release and update the versions of the packages.
# It's triggered manually once the team is ready to push a new release.
name: "Release Step 3: Create Release PR (create-release-pr.yaml)"

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create-release-pr:
    name: Create Release PR
    runs-on: blacksmith-8vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5.82
        with:
          # Run `release-plz release-pr` command.
          command: release-pr
          # Removed version pin - using latest to debug 0000000 error
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
