[package]
name = "solana-axelar-governance"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
description = "Axelar Governance Anchor program for Solana"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_axelar_governance"

[features]
default = ["devnet-amplifier"]
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
test-sbf = []

devnet-amplifier = [
	"solana-axelar-gateway/devnet-amplifier",
]
stagenet = [
	"solana-axelar-gateway/stagenet",
]
testnet = [
	"solana-axelar-gateway/testnet",
]
mainnet = [
	"solana-axelar-gateway/mainnet",
]

[dependencies]
alloy-sol-types.workspace = true
governance-gmp.workspace = true
solana-axelar-std.workspace = true
solana-axelar-gateway = { workspace = true, features = ["no-entrypoint", "cpi"], default-features = false }
solana-keccak-hasher.workspace = true
anchor-lang.workspace = true
anchor-spl.workspace = true

[package.metadata.cargo-machete]
ignored = ["anchor-spl"]

[dev-dependencies]
libsecp256k1.workspace = true
solana-axelar-memo = { workspace = true, features = ["no-entrypoint", "cpi"], default-features = false }
solana-sdk.workspace = true
solana-sdk-ids.workspace = true
solana-axelar-gateway-test-fixtures.workspace = true
solana-axelar-governance-test-fixtures.workspace = true
mollusk-svm.workspace = true
hex.workspace = true
