[package]
name = "solana-axelar-governance"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_axelar_governance"

[features]
default = ["devnet-amplifier"]
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
test-sbf = []

devnet-amplifier = [
	"solana-axelar-gateway/devnet-amplifier",
	"solana-axelar-gateway-test-fixtures/devnet-amplifier",
	"solana-axelar-governance-legacy/devnet-amplifier",
]
stagenet = [
	"solana-axelar-gateway/stagenet",
	"solana-axelar-gateway-test-fixtures/stagenet",
	"solana-axelar-governance-legacy/stagenet",
]
testnet = [
	"solana-axelar-gateway/testnet",
	"solana-axelar-gateway-test-fixtures/testnet",
	"solana-axelar-governance-legacy/testnet",
]
mainnet = [
	"solana-axelar-gateway/mainnet",
	"solana-axelar-gateway-test-fixtures/mainnet",
	"solana-axelar-governance-legacy/mainnet",
]

[dependencies]
alloy-sol-types.workspace = true
governance-gmp.workspace = true
solana-axelar-gateway = { workspace = true, features = ["no-entrypoint", "cpi"], default-features = false }
anchor-lang.workspace = true
program-utils.workspace = true

[dev-dependencies]
solana-axelar-governance-legacy = { workspace = true, features = ["no-entrypoint"], default-features = false }
libsecp256k1.workspace = true
bincode.workspace = true
solana-axelar-memo = { workspace = true, features = ["no-entrypoint", "cpi"], default-features = false }
solana-sdk.workspace = true
solana-axelar-gateway-test-fixtures.workspace = true
solana-axelar-governance-test-fixtures.workspace = true
mollusk-svm.workspace = true
hex.workspace = true
